using System.Buffers.Binary;
using Nightrunner.Core.Mesh.ClassReader;
using Nightrunner.Core.Rpack;

namespace Nightrunner.Core.Prefab;

/// <summary>Thrown when a <c>Prefabs</c> resource is malformed or an edit would break a loader requirement.</summary>
public sealed class PrefabFormatException(string message) : Exception(message);

/// <summary>
/// The binary <c>Prefabs</c> resource (RPACK type 0x61) of Dying Light: The Beast: part 0x61 is the primary image,
/// part 0x62 the metadata (8-byte prefix + ClassReader stream + secondary image). Spec: prefab format notes
/// (2026-09-24) §2–5 and §9.
/// </summary>
/// <remarks>
/// <code>
/// part 0x62:
/// 0x00 u32 nPrefab            cbs::Prefab roots (0xC0000033)
/// 0x04 u32 nPresets           CRttiClassPresets roots (0xC0000067)
/// 0x08 u32 primary_size       == part 0x61 size
/// 0x0C u32 record_count
/// 0x10 u32 object_count_raw   bit 31 = secondary image present; low 31 bits = nPrefab + nPresets
/// 0x14 {u32 offset, u32 class_id, u32 count_flags} × records   (bit 30 secondary, bit 31 reverse)
///      u32 slot_count, u32 slot_offset × S, u8 slot_kind × S
///      align 4 (part-relative), u32 secondary_size, align 16 (part-relative), secondary image to EOF
/// </code>
/// The part is <b>not</b> the mesh <see cref="Fixups"/> stream at +8: its alignments are relative to the part start,
/// which moves the align-16 pad by 8 bytes. Header words that are derivable (record, slot and secondary counts) are
/// regenerated by <see cref="EncodeMetadata"/>; the others (prefix, primary_size, object_count_raw) and every pad are
/// kept raw, so a parsed resource re-encodes byte for byte and <see cref="Validate"/> reports any inconsistency.
/// </remarks>
public sealed class PrefabContainer
{
    public const byte PartImage = 0x61;
    public const byte PartMeta = 0x62;
    public const byte ResourceType = 0x61;
    public const uint SecondaryPresent = 0x80000000;
    public const int PrefixSize = 8;
    public const int RootStride = 0x260;

    // record flag bits (count_flags)
    public const uint RecInSecondary = 0x40000000;
    public const uint RecReverse = 0x80000000;
    public const uint RecCountMask = 0x3FFFFFFF;

    // slot kind bits
    public const byte KindIndirect = 0x1;
    public const byte KindTagged = 0x2;
    public const byte KindSlotSecondary = 0x4;
    public const byte KindTargetSecondary = 0x8;

    /// <summary>Kinds the loader accepts (§9.6): 0/2 primary→primary, 9/11 primary→element, 12/14 inside secondary,
    /// 4/6 secondary→primary. Never 8 or 10 (the secondary image is freed after load).</summary>
    public static readonly byte[] AllowedKinds = [0, 2, 4, 6, 9, 11, 12, 14];

    public const ulong OffsetMask = 0xFFFF_FFFF_FFFF;
    public const ushort StringTag = 0x2100;

    public uint PrefabCount { get; set; }
    public uint PresetCount { get; set; }

    /// <summary>Header word 0x08, raw.</summary>
    public uint PrimarySizeField { get; set; }

    /// <summary>Header word 0x10, raw.</summary>
    public uint ObjectCountRaw { get; set; }

    public List<Record> Records { get; }
    public List<Slot> Slots { get; }

    /// <summary>Part 0x61 (mutable: edits write slot words in place or replace the array).</summary>
    public byte[] Primary { get; set; }

    /// <summary>The secondary image (metadata tail); null when header bit 31 is clear.</summary>
    public byte[]? Secondary { get; set; }

    /// <summary>Align-4 pad after the slot kinds and align-16 pad after the size word, kept verbatim.</summary>
    public byte[] PadAfterKinds { get; set; }
    public byte[] PadAfterSize { get; set; }

    /// <summary>Bytes after the parsed stream (none in any shipped pack), kept verbatim.</summary>
    public byte[] Trailing { get; set; }

    public PrefabContainer(uint prefabCount, uint presetCount, uint primarySizeField, uint objectCountRaw,
                           List<Record> records, List<Slot> slots, byte[] primary, byte[]? secondary,
                           byte[]? padAfterKinds = null, byte[]? padAfterSize = null, byte[]? trailing = null)
    {
        PrefabCount = prefabCount;
        PresetCount = presetCount;
        PrimarySizeField = primarySizeField;
        ObjectCountRaw = objectCountRaw;
        Records = records;
        Slots = slots;
        Primary = primary;
        Secondary = secondary;
        PadAfterKinds = padAfterKinds ?? [];
        PadAfterSize = padAfterSize ?? [];
        Trailing = trailing ?? [];
    }

    public bool SecondaryFlag => (ObjectCountRaw & SecondaryPresent) != 0;
    public uint ObjectCount => ObjectCountRaw & 0x7FFFFFFF;
    public int RootCount => (int)(PrefabCount + PresetCount);
    public int SecondarySize => Secondary?.Length ?? 0;

    // ---- parse / encode -----------------------------------------------------------------------------------

    /// <summary>Parts 0x61 and 0x62 of the logical resource at <paramref name="logicalIndex"/>.</summary>
    public static (byte[] Primary, byte[] Meta) ReadParts(RpackFile pack, int logicalIndex)
    {
        var lg = pack.Logicals[logicalIndex];
        string name = pack.Name(logicalIndex);
        if (lg.Type != ResourceType)
            throw new PrefabFormatException($"'{name}' is type 0x{lg.Type:X2}, not a Prefabs resource (0x61)");
        byte[]? image = null, meta = null;
        for (int k = 0; k < lg.PartCount; k++)
        {
            int phys = (int)lg.FirstPart + k;
            byte t = pack.PartType(phys);
            if (t is not (PartImage or PartMeta))
                throw new PrefabFormatException($"'{name}': unexpected part 0x{t:X2}");
            if (pack.PartUnreadableReason(phys) is { } why)
                throw new PrefabFormatException($"'{name}': part 0x{t:X2} unreadable — {why}");
            if ((t == PartImage ? image : meta) is not null)
                throw new PrefabFormatException($"'{name}': part 0x{t:X2} appears twice");
            if (t == PartImage) image = pack.ReadPart(phys);
            else meta = pack.ReadPart(phys);
        }
        if (image is null) throw new PrefabFormatException($"'{name}': missing part 0x61 (primary image)");
        if (meta is null) throw new PrefabFormatException($"'{name}': missing part 0x62 (metadata)");
        return (image, meta);
    }

    /// <summary>Every type-0x61 logical index of a pack (one <c>Prefabs</c> per prefab-bearing pack).</summary>
    public static int[] ResourcesIn(RpackFile pack) =>
        Enumerable.Range(0, pack.Count).Where(i => pack.Logicals[i].Type == ResourceType).ToArray();

    public static PrefabContainer Read(RpackFile pack, int logicalIndex)
    {
        var (image, meta) = ReadParts(pack, logicalIndex);
        return Parse(image, meta);
    }

    public static PrefabContainer Parse(byte[] primary, ReadOnlySpan<byte> meta)
    {
        int n = meta.Length;
        if (n < PrefixSize + 12 + 4)
            throw new PrefabFormatException($"prefab metadata too short ({n} bytes)");
        uint nPrefab = U32(meta, 0), nPresets = U32(meta, 4);
        uint primarySize = U32(meta, 8), recordCount = U32(meta, 12), objRaw = U32(meta, 16);
        long pos = 20;
        if (recordCount > (n - pos) / 12)
            throw new PrefabFormatException($"prefab metadata: {recordCount} records do not fit in {n} bytes");
        var records = new List<Record>((int)recordCount);
        for (int i = 0; i < recordCount; i++)
        {
            int o = (int)pos + i * 12;
            records.Add(new Record(U32(meta, o), U32(meta, o + 4), U32(meta, o + 8)));
        }
        pos += recordCount * 12L;
        if (pos + 4 > n) throw new PrefabFormatException("prefab metadata: slot count missing");
        uint slotCount = U32(meta, (int)pos);
        pos += 4;
        if (slotCount > (n - pos) / 5)
            throw new PrefabFormatException($"prefab metadata: {slotCount} slots do not fit in {n} bytes");
        var slots = new List<Slot>((int)slotCount);
        int kinds = (int)(pos + slotCount * 4L);
        for (int i = 0; i < slotCount; i++) slots.Add(new Slot(U32(meta, (int)pos + i * 4), meta[kinds + i]));
        pos = kinds + slotCount;
        byte[]? secondary = null;
        byte[] pad1 = [], pad2 = [];
        if ((objRaw & SecondaryPresent) != 0)
        {
            long p4 = Align(pos, 4);
            if (p4 + 4 > n) throw new PrefabFormatException("prefab metadata: secondary size word missing");
            pad1 = meta[(int)pos..(int)p4].ToArray();
            uint secSize = U32(meta, (int)p4);
            long p16 = Align(p4 + 4, 16);
            if (p16 > n || secSize > n - p16)
                throw new PrefabFormatException($"prefab metadata: secondary image of {secSize} bytes does not fit");
            pad2 = meta[(int)(p4 + 4)..(int)p16].ToArray();
            secondary = meta.Slice((int)p16, (int)secSize).ToArray();
            pos = p16 + secSize;
        }
        return new PrefabContainer(nPrefab, nPresets, primarySize, objRaw, records, slots, primary, secondary,
                                   pad1, pad2, meta[(int)pos..].ToArray());
    }

    /// <summary>Part 0x62 from the model: record, slot and secondary counts are derived; everything else is raw.</summary>
    public byte[] EncodeMetadata()
    {
        var sec = Secondary ?? [];
        bool hasSec = SecondaryFlag;
        int size = 20 + Records.Count * 12 + 4 + Slots.Count * 5;
        if (hasSec)
        {
            if (PadAfterKinds.Length != Align(size, 4) - size)
                throw new PrefabFormatException($"align-4 pad is {PadAfterKinds.Length} bytes, the layout needs {Align(size, 4) - size}");
            size = (int)Align(size, 4) + 4;
            if (PadAfterSize.Length != Align(size, 16) - size)
                throw new PrefabFormatException($"align-16 pad is {PadAfterSize.Length} bytes, the layout needs {Align(size, 16) - size}");
            size = (int)Align(size, 16) + sec.Length;
        }
        else if (Secondary is not null)
            throw new PrefabFormatException("a secondary image is present but header bit 31 is clear");
        var out_ = new byte[size + Trailing.Length];
        var s = out_.AsSpan();
        W32(s, 0, PrefabCount);
        W32(s, 4, PresetCount);
        W32(s, 8, PrimarySizeField);
        W32(s, 12, (uint)Records.Count);
        W32(s, 16, ObjectCountRaw);
        int pos = 20;
        foreach (var r in Records)
        {
            W32(s, pos, r.Offset); W32(s, pos + 4, r.ClassRaw); W32(s, pos + 8, r.FlagsRaw);
            pos += 12;
        }
        W32(s, pos, (uint)Slots.Count);
        pos += 4;
        for (int i = 0; i < Slots.Count; i++) W32(s, pos + i * 4, Slots[i].Offset);
        pos += Slots.Count * 4;
        for (int i = 0; i < Slots.Count; i++) s[pos + i] = Slots[i].Kind;
        pos += Slots.Count;
        if (hasSec)
        {
            PadAfterKinds.CopyTo(s[pos..]);
            pos += PadAfterKinds.Length;
            W32(s, pos, (uint)sec.Length);
            pos += 4;
            PadAfterSize.CopyTo(s[pos..]);
            pos += PadAfterSize.Length;
            sec.CopyTo(s[pos..]);
            pos += sec.Length;
        }
        Trailing.CopyTo(s[pos..]);
        return out_;
    }

    /// <summary>Part 0x61 as it would be written (the primary image itself).</summary>
    public byte[] EncodePrimary() => Primary;

    /// <summary>
    /// Recomputes the derived raw words after an edit: primary_size, object_count_raw (roots + secondary bit) and the
    /// two pads for the current table sizes. A parsed, unedited resource is unchanged by this.
    /// </summary>
    public void Sync()
    {
        PrimarySizeField = (uint)Primary.Length;
        ObjectCountRaw = (uint)(PrefabCount + PresetCount) | (Secondary is not null ? SecondaryPresent : 0);
        if (Secondary is null) { PadAfterKinds = []; PadAfterSize = []; return; }
        int size = 20 + Records.Count * 12 + 4 + Slots.Count * 5;
        PadAfterKinds = new byte[Align(size, 4) - size];
        size = (int)Align(size, 4) + 4;
        PadAfterSize = new byte[Align(size, 16) - size];
    }

    public PrefabContainer Clone() =>
        new(PrefabCount, PresetCount, PrimarySizeField, ObjectCountRaw, [.. Records], [.. Slots],
            (byte[])Primary.Clone(), (byte[]?)Secondary?.Clone(), (byte[])PadAfterKinds.Clone(),
            (byte[])PadAfterSize.Clone(), (byte[])Trailing.Clone());

    // ---- pointers -----------------------------------------------------------------------------------------

    public byte[] ImageOf(bool secondary) =>
        secondary ? Secondary ?? throw new PrefabFormatException("no secondary image") : Primary;

    /// <summary>Decodes a slot: the image and offset of its word, the target image and offset, and the tag.</summary>
    public SlotTarget Target(Slot s)
    {
        bool inSec = (s.Kind & KindSlotSecondary) != 0, toSec = (s.Kind & KindTargetSecondary) != 0;
        var img = ImageOf(inSec);
        if (s.Offset > img.Length - 8L)
            throw new PrefabFormatException($"slot at 0x{s.Offset:X} (kind {s.Kind}) lies outside its image");
        ulong w = BinaryPrimitives.ReadUInt64LittleEndian(img.AsSpan((int)s.Offset, 8));
        bool tagged = (s.Kind & KindTagged) != 0;
        ulong masked = tagged ? w & OffsetMask : w;
        long target = masked == 0 ? -1 : (long)(masked - 1);
        return new SlotTarget(inSec, (int)s.Offset, toSec, target, tagged ? (ushort)(w >> 48) : (ushort)0, w);
    }

    // ---- records --------------------------------------------------------------------------------------------

    /// <summary>
    /// [start, end) of every record in its own image: end = next record of the same image in table order (records
    /// ascend within each image), or the image size for the last.
    /// </summary>
    public (int Start, int End)[] Spans()
    {
        var spans = new (int, int)[Records.Count];
        int nextPrim = Primary.Length, nextSec = SecondarySize;
        for (int i = Records.Count - 1; i >= 0; i--)
        {
            var r = Records[i];
            bool sec = (r.FlagsRaw & RecInSecondary) != 0;
            spans[i] = ((int)r.Offset, sec ? nextSec : nextPrim);
            if (sec) nextSec = (int)r.Offset; else nextPrim = (int)r.Offset;
        }
        return spans;
    }

    // ---- validation ---------------------------------------------------------------------------------------

    /// <summary>
    /// Null when the roots have the Dying Light: The Beast layout (cbs::Prefab 0x260 B at a 0x260 stride); otherwise
    /// why not. Dying Light 2 packs parse and round-trip with the same codec, but their prefab roots are 0x228 B and
    /// their element text pointers are untagged kind-12 slots, and their secondary image holds a fourth element class
    /// (0xC0000070); that layout is refused by <see cref="Validate"/> and the edits; the decoder reads it with <see cref="PrefabLayout"/>.
    /// </summary>
    public string? LayoutProblem()
    {
        var spans = Spans();
        for (int i = 0; i < PrefabCount && i < Records.Count; i++)
        {
            int span = spans[i].End - spans[i].Start;
            if (Records[i].ClassRaw == PrefabClasses.Prefab && span < RootStride)
                return $"prefab root {i} spans 0x{span:X} bytes, less than the 0x260-byte cbs::Prefab of Dying Light: " +
                       "The Beast (Dying Light 2 roots are 0x228): layout not supported";
        }
        int untagged = Slots.Count(s => s.Kind == (KindSlotSecondary | KindTargetSecondary));
        if (untagged > 0)
            return $"{untagged} kind-12 slots (untagged text pointers inside the secondary image, the Dying Light 2 form; " +
                   "Dying Light: The Beast element text is tagged 0x2100, kind 14): layout not supported";
        return null;
    }

    /// <summary>Throws when <see cref="LayoutProblem"/> reports one.</summary>
    public void RequireDltbLayout()
    {
        if (LayoutProblem() is { } why) throw new PrefabFormatException($"unsupported Prefabs layout: {why}");
    }

    /// <summary>Throws with every broken loader requirement (§9) by name; see <see cref="Problems"/>.</summary>
    public void Validate()
    {
        var p = Problems();
        if (p.Count == 0) return;
        var head = string.Join("; ", p.Take(8));
        throw new PrefabFormatException(p.Count > 8 ? $"{head}; … {p.Count - 8} more" : head);
    }

    /// <summary>
    /// The loader requirements of §9 checked offline (the engine validates nothing and crashes instead):
    /// header counts, root partition and stride, record partition, alignment, allowed slot kinds, slot order,
    /// null-pointer rule, element targets of indirect slots, readable element text, names, and root flags.
    /// </summary>
    public List<string> Problems(int limit = 64)
    {
        var p = new List<string>();
        void Add(string s) { if (p.Count < limit) p.Add(s); }

        // header (§9.1, §9.9)
        uint roots = PrefabCount + PresetCount;
        if (ObjectCount != roots)
            Add($"object_count {ObjectCount} != nPrefab {PrefabCount} + nPresets {PresetCount}");
        if (SecondaryFlag != (Secondary is not null))
            Add(SecondaryFlag ? "header bit 31 set but no secondary image" : "secondary image present but header bit 31 clear");
        if (PrimarySizeField != Primary.Length)
            Add($"primary_size {PrimarySizeField} != part 0x61 size {Primary.Length}");
        // §9.9 asks for a multiple of 16, but 6 of the 23 shipped DLTB packs end on an 8-byte boundary (e.g.
        // dlc_frontier_persistent_pc, 67,762,952 B); records are 8-aligned, so 8 is what the data supports.
        if (Primary.Length % 8 != 0) Add($"primary image size {Primary.Length} is not a multiple of 8");
        if (PadAfterKinds.Any(b => b != 0) || PadAfterSize.Any(b => b != 0)) Add("non-zero metadata padding");
        if (Trailing.Length != 0) Add($"{Trailing.Length} bytes after the secondary image (it must end at EOF)");
        if (Records.Count < roots) { Add($"{Records.Count} records < {roots} roots"); return p; }
        if (LayoutProblem() is { } layout) { Add(layout); return p; }

        // roots (§9.2)
        for (int i = 0; i < roots; i++)
        {
            var r = Records[i];
            bool prefab = i < PrefabCount;
            uint want = prefab ? PrefabClasses.Prefab : PrefabClasses.ClassPresets;
            if (r.ClassRaw != want) Add($"root {i}: class 0x{r.ClassRaw:X8}, expected 0x{want:X8} (roots first: prefabs, then presets)");
            if (r.FlagsRaw != 1) Add($"root {i}: count_flags 0x{r.FlagsRaw:X8}, expected 1 (primary, count 1, not reverse)");
            if (prefab && r.Offset != (uint)(RootStride * i)) Add($"root {i}: offset 0x{r.Offset:X}, expected 0x{RootStride * i:X} (0x260 stride)");
        }

        // partition (§9.3) and alignment (§9.9)
        int firstReverse = Records.Count;
        for (int i = 0; i < Records.Count; i++)
            if ((Records[i].FlagsRaw & RecReverse) != 0) { firstReverse = i; break; }
        long lastPrim = -1, lastSec = -1;
        bool sawPrim = false, sawSec = false;
        for (int i = 0; i < Records.Count; i++)
        {
            var r = Records[i];
            bool rev = (r.FlagsRaw & RecReverse) != 0, sec = (r.FlagsRaw & RecInSecondary) != 0;
            if (i >= firstReverse && !rev) Add($"record {i}: forward record after the first reverse record {firstReverse} (never constructed)");
            if (rev != sec) Add($"record {i}: reverse bit {(rev ? 1 : 0)} != secondary bit {(sec ? 1 : 0)}");
            if (sec && !PrefabClasses.IsResolveElement(r.ClassRaw)) Add($"record {i}: class 0x{r.ClassRaw:X8} in the secondary image (only B1000000/C0000042/C0000043)");
            if ((r.FlagsRaw & RecCountMask) == 0) Add($"record {i}: element count 0");
            if (!PrefabClasses.InKnownNamespace(r.ClassRaw)) Add($"record {i}: class 0x{r.ClassRaw:X8} outside every Construct namespace");
            if (r.Offset % 8 != 0) Add($"record {i}: offset 0x{r.Offset:X} not 8-aligned");
            int imgLen = sec ? SecondarySize : Primary.Length;
            if (r.Offset >= imgLen) Add($"record {i}: offset 0x{r.Offset:X} outside its image (0x{imgLen:X})");
            ref long last = ref sec ? ref lastSec : ref lastPrim;
            if (r.Offset <= last) Add($"record {i}: offset 0x{r.Offset:X} does not rise within its image");
            if (sec && !sawSec && r.Offset != 0) Add($"secondary image does not start with a record (first at 0x{r.Offset:X})");
            if (!sec && !sawPrim && r.Offset != 0) Add($"primary image does not start with a record (first at 0x{r.Offset:X})");
            if (sec) sawSec = true; else sawPrim = true;
            last = r.Offset;
        }
        if (p.Count > 0) return p;
        var spans = Spans();
        for (int i = 0; i < Records.Count; i++)
        {
            var r = Records[i];
            if (PrefabClasses.Stride(r.ClassRaw) is { } stride && (long)stride * r.Count > spans[i].End - spans[i].Start)
                Add($"record {i}: {r.Count} × 0x{stride:X} bytes of 0x{r.ClassRaw:X8} overrun its span of 0x{spans[i].End - spans[i].Start:X}");
        }

        // slots (§9.4–9.7)
        var allowed = new HashSet<byte>(AllowedKinds);
        var elementAt = new Dictionary<uint, int>();
        for (int i = firstReverse; i < Records.Count; i++) elementAt.TryAdd(Records[i].Offset, i);
        int firstIndirect = -1;
        var seenPrim = new HashSet<uint>();
        var seenSec = new HashSet<uint>();
        for (int i = 0; i < Slots.Count; i++)
        {
            var s = Slots[i];
            if (!allowed.Contains(s.Kind)) { Add($"slot {i} at 0x{s.Offset:X}: kind {s.Kind} is not allowed{(s.Kind is 8 or 10 ? " (a persistent pointer into the freed secondary image)" : "")}"); continue; }
            bool indirect = (s.Kind & KindIndirect) != 0;
            if (indirect && firstIndirect < 0) firstIndirect = i;
            if (!indirect && firstIndirect >= 0) Add($"slot {i} at 0x{s.Offset:X}: direct kind {s.Kind} after the first indirect slot {firstIndirect} (it would be dereferenced)");
            bool inSec = (s.Kind & KindSlotSecondary) != 0;
            if (s.Offset % 8 != 0) Add($"slot {i}: offset 0x{s.Offset:X} not 8-aligned");
            if (!(inSec ? seenSec : seenPrim).Add(s.Offset)) Add($"slot {i}: second slot at {(inSec ? "secondary" : "primary")} 0x{s.Offset:X}");
            if (inSec && Secondary is null) { Add($"slot {i}: kind {s.Kind} but no secondary image"); continue; }
            if (s.Offset > ImageOf(inSec).Length - 8L) { Add($"slot {i}: offset 0x{s.Offset:X} outside its image"); continue; }
            var t = Target(s);
            if (t.Target < 0) { Add($"slot {i} at 0x{s.Offset:X}: null word (a null pointer has no slot)"); continue; }
            if (t.ToSecondary && Secondary is null) { Add($"slot {i}: targets the secondary image but there is none"); continue; }
            if (t.Target >= ImageOf(t.ToSecondary).Length) Add($"slot {i} at 0x{s.Offset:X}: target 0x{t.Target:X} outside its image");
            if (indirect && !(elementAt.TryGetValue((uint)t.Target, out int rec) && PrefabClasses.IsResolveElement(Records[rec].ClassRaw)))
                Add($"slot {i} at 0x{s.Offset:X}: indirect target 0x{t.Target:X} is not +0 of a resolve element");
        }
        if (p.Count > 0) return p;

        // resolve elements must carry readable text (§9.7); names and flags of the roots (§9.11, §9.12)
        var reader = new PrefabText(this);
        for (int i = firstReverse; i < Records.Count; i++)
            if (PrefabClasses.IsResolveElement(Records[i].ClassRaw))
                for (int k = 0; k < Records[i].Count; k++)
                    if (reader.ElementText(i, k) is null)
                        Add($"record {i} (0x{Records[i].ClassRaw:X8}) element {k}: text unreadable");
        var names = new Dictionary<string, int>(StringComparer.Ordinal);
        for (int i = 0; i < PrefabCount; i++)
        {
            int root = (int)Records[i].Offset;
            string? name = reader.PstringAt(false, root + 0x10);
            if (name is null) { Add($"prefab {i}: no name at +0x10"); continue; }
            if (!names.TryAdd(name, i)) Add($"prefab {i}: name '{name}' already used by prefab {names[name]}");
            if (name != name.ToLowerInvariant()) Add($"prefab {i}: name '{name}' is not lowercase");
            if (name.EndsWith(".prefab", StringComparison.Ordinal) || name.EndsWith(".eds", StringComparison.Ordinal))
                Add($"prefab {i}: name '{name}' keeps its extension");
            byte flags = Primary[root + 0x259];
            if ((flags & 0x81) != 0) Add($"prefab {i}: +0x259 flags 0x{flags:X2} (bits 0x80/0x01 must be clear on disk)");
        }
        return p;
    }

    // ---- helpers ------------------------------------------------------------------------------------------

    internal static uint U32(ReadOnlySpan<byte> b, int o) => BinaryPrimitives.ReadUInt32LittleEndian(b[o..]);
    internal static void W32(Span<byte> b, int o, uint v) => BinaryPrimitives.WriteUInt32LittleEndian(b[o..], v);
    internal static long Align(long v, int a) => (v + a - 1) / a * a;
}

/// <summary>
/// A decoded slot: where its word lies, where it points, and its tag. <see cref="Target"/> is −1 for a zero word.
/// </summary>
public readonly record struct SlotTarget(bool InSecondary, int Offset, bool ToSecondary, long Target, ushort Tag, ulong Word);
