<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Mesh\" />
    <Folder Include="Audio\" />
    <Folder Include="Model\" />
    <Folder Include="Mat\" />
    <Folder Include="Texture\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nightrunner.Tests" />
  </ItemGroup>

</Project>
